apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: schmidtjonathan1-poi-map-app-dev
  annotations:
    argocd/app-name: schmidtjonathan1-poi-map-app-dev
    backstage.io/kubernetes-id: schmidtjonathan1-poi-map-app
    backstage.io/kubernetes-namespace: schmidtjonathan1
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-demo/schmidtjonathan1-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/dev-pipelines/ns/schmidtjonathan1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/k8s/ns/schmidtjonathan1/deployments/schmidtjonathan1-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-pzz6v.9nln.p1.openshiftapps.com/#https://github.com/rhdh23-demo/schmidtjonathan1-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://schmidtjonathan1-poi-map-app-schmidtjonathan1.apps.rosa-pzz6v.9nln.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/schmidtjonathan1"
  system: workshop-system-schmidtjonathan1
  consumesApis:
    - gateway-api-schmidtjonathan1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-schmidtjonathan1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/schmidtjonathan1"
